export const events = [
  {
    title: 'Galery Opening',
    description:
      'Discover an enchanting evening celebrating the world of art at our exclusive gallery opening.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Art',
    picture: 'Art',
    priority: 'High',
    id: 1,
  },
  {
    title: 'Innovation Summit',
    description:
      'Engage in a thought-provoking journey of knowledge and collaboration at our Innovation Summit. ',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Conference',
    picture: 'Conference',
    priority: 'Medium',
    id: 2,
  },
  {
    title: 'Empower Your Creativity',
    description:
      'Ignite your creativity and nurture your storytelling skills in our immersive Creative Writing Workshop. ',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Workshop',
    picture: 'Workshop',
    priority: 'High',
    id: 3,
  },
  {
    title: 'Summer Soiree',
    description:
      'Embrace the tropical vibes and escape to paradise at our Beach Luau Extravaganza.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Party',
    picture: 'Party',
    priority: 'High',
    id: 4,
  },
  {
    title: 'Leadership Conference',
    description:
      'Unlock the secrets of effective leadership at our transformative Success Leadership Conference.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Business',
    picture: 'Business',
    priority: 'Medium',
    id: 5,
  },
  {
    title: 'Tech Startup Showcase',
    description:
      'Witness the future of technology as innovative startups showcase their groundbreaking ideas.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Workshop',
    picture: 'Workshop2',
    priority: 'Low',
    id: 6,
  },
  {
    title: 'Acoustic Garden Concert',
    description:
      'Experience the magic of live music amidst the serene beauty of nature at our Acoustic Garden Concert.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Music',
    picture: 'Music',
    priority: 'High',
    id: 7,
  },
  {
    title: 'Extreme Adventure Race',
    description:
      'Calling all thrill-seekers! Embark on an adrenaline-pumping journey at our Extreme Adventure Race.',
    data: '12.07',
    time: '12:00',
    location: 'Kyiv',
    category: 'Sport',
    picture: 'Sport',
    priority: 'Low',
    id: 8,
  },
];
